name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: 'false'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build SystemRelease
      run: ./gradlew assembleSystemRelease
      
    - name: Build GeckoRelease
      run: ./gradlew assembleGeckoRelease
      
    - name: Build SystemDebug
      run: ./gradlew assembleSystemDebug
      
    - name: Build GeckoDebug
      run: ./gradlew assembleGeckoDebug
      
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: ./app/build/outputs/apk/system/release
        signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
        alias: ${{ secrets.DEBUG_ALIAS }}
        keyStorePassword: ${{ secrets.DEBUG_KEY_PASSWORD }}
        keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}   
    - uses: actions/upload-artifact@v2
      with:
        name: WebView release
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app1
      with:
        releaseDirectory: ./app/build/outputs/apk/system/debug
        signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
        alias: ${{ secrets.DEBUG_ALIAS }}
        keyStorePassword: ${{ secrets.DEBUG_KEY_PASSWORD }}
        keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}   
    - uses: actions/upload-artifact@v2
      with:
        name: WebView debug
        path: ${{steps.sign_app1.outputs.signedReleaseFile}}
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app2
      with:
        releaseDirectory: ./app/build/outputs/apk/gecko/release
        signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
        alias: ${{ secrets.DEBUG_ALIAS }}
        keyStorePassword: ${{ secrets.DEBUG_KEY_PASSWORD }}
        keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}   
    - uses: actions/upload-artifact@v2
      with:
        name: Gecko release
        path: ${{steps.sign_app2.outputs.signedReleaseFile}}
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app3
      with:
        releaseDirectory: ./app/build/outputs/apk/gecko/debug
        signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
        alias: ${{ secrets.DEBUG_ALIAS }}
        keyStorePassword: ${{ secrets.DEBUG_KEY_PASSWORD }}
        keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}   
    - uses: actions/upload-artifact@v2
      with:
        name: Gecko debug
        path: ${{steps.sign_app3.outputs.signedReleaseFile}}
      
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
